# Generated by Django 5.1.1 on 2024-12-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canine',
            name='adviser',
        ),
        migrations.AlterField(
            model_name='canine',
            name='picture',
            field=models.CharField(max_length=255),
        ),
    ]
