# Generated by Django 5.1.1 on 2024-10-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(default=None),
        ),
    ]
