# Generated by Django 5.1.1 on 2024-12-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_canine_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canine',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
