# Generated by Django 5.1.2 on 2024-10-22 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
