# Generated by Django 5.1.2 on 2024-10-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_adviser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canine',
            name='name',
        ),
        migrations.AddField(
            model_name='bill',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
