# Generated by Django 5.1.2 on 2024-10-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_remove_canine_name_bill_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adviser',
            options={'permissions': [('view_canine_model', 'Can view canine model'), ('add_canine_model', 'Can add canine model'), ('change_canine_model', 'Can change canine model'), ('delete_canine_model', 'Can delete canine model')]},
        ),
    ]
